apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    # bash [echo -n "samkb420" | base64 ]
    mongo-root-username: c2Fta2I0MjA=  
    # bash [echo -n "iampassword" | base64 ]
    mongo-root-password: aWFtcGFzc3dvcmQ=

